Repository FehamIsmail/-hiza_tech-soen341project2023-, pull requests merged in 2023-02, with the labels that each got.

#8 Added a table to clarify team members roles #5
  README.md
Labels: documentation

#10 Completed README.md for sprint 1
  README.md
Labels: documentation

#21 [Issue #20] Added react-typescript frontend component
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo_256x.png
  frontend/public/manifest.json
  frontend/src/components/App/App.test.tsx
  frontend/src/components/App/App.tsx
  frontend/src/index.tsx
  frontend/src/setupTests.tsx
  frontend/tsconfig.json
Labels: User Story

#31 [Frontend] #30 Setting up TailwindCSS on React
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/output.css
  frontend/src/assets/logo_nobg.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/input.css
  frontend/src/react-app-env.d.ts
  frontend/src/scripts/utils.tsx
  frontend/tailwind.config.js
  package-lock.json
  package.json
Labels: Sub-task, dev setup

#40 Designed the banner, closes #39
  frontend/public/logo_256x_old.png
  frontend/src/assets/CC.png
  frontend/src/assets/banner_bg.png
  frontend/src/assets/banner_bg_purple.png
  frontend/src/components/App/App.tsx
  frontend/src/components/Banner/Banner.tsx
  frontend/tailwind.config.js
Labels: enhancement, Sub-task

#44 Edited banner + added typing animation #38
  frontend/src/components/App/App.tsx
  frontend/src/components/Banner/Banner.tsx
  frontend/src/components/SearchBar/search.tsx
  frontend/tailwind.config.js
Labels: Task

#45 created 10 mock jobs and installed recoil/lorem-ipsum closes #41
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/mockJobs.tsx
  frontend/src/constants/types.tsx
Labels: Sub-task
